import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, existsSync, readFileSync, writeFileSync } from "fs";
import dayjs from "dayjs";
import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill';
import { NodeModulesPolyfillPlugin } from '@esbuild-plugins/node-modules-polyfill';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const copyStaticFiles = {
	name: "copy-static-files",
	setup(build) {
		build.onEnd(() => {
			[
				"styles.css",
				".hotreload"
			].forEach(file => {
				if (existsSync(file)) {
					copyFileSync(file, `dist/${file}`);
				}
			});
		});
	},
};

const copyManifest = {
	name: "development-manifest",
	setup(build) {
		build.onEnd(() => {
			const srcPath = "manifest.json";
			const destPath = `dist/${srcPath}`;

			if (prod) {
				copyFileSync(srcPath, destPath);
			} else {
				const manifest = JSON.parse(readFileSync(srcPath, { encoding: 'utf-8' }));
				const suffix = dayjs().format('YYYYMMDD-hhmm');
				manifest.version = `${manifest.version}-dev-${suffix}`;
				writeFileSync(destPath, JSON.stringify(manifest, null, '\t'), { encoding: 'utf-8' });
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules
	],
	format: "cjs",
	target: "es2018",
	platform: "browser",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: "dist",
	minify: prod,
	define: {
		"process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development"),
		"global": "window",
	},
	plugins: [
		copyStaticFiles,
		copyManifest,
		NodeGlobalsPolyfillPlugin({
			process: true,
			buffer: true,
		}),
		NodeModulesPolyfillPlugin({
			modules: {
				'events': true,
				'stream': true,
				'util': true,
				'crypto': 'empty',
				'fs': 'empty',
				'path': 'empty',
				'os': 'empty',
			}
		})
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
