import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill';
import { NodeModulesPolyfillPlugin } from '@esbuild-plugins/node-modules-polyfill';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules
	],
	format: "cjs",
	target: "es2018",
	platform: "browser",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	define: {
		"process.env.NODE_ENV": JSON.stringify(prod ? "production" : "development"),
		"global": "window",
	},
	plugins: [
		NodeGlobalsPolyfillPlugin({
			process: true,
			buffer: true,
		}),
		NodeModulesPolyfillPlugin({
			modules: {
				'events': true,
				'stream': true,
				'util': true,
				'crypto': 'empty',
				'fs': 'empty',
				'path': 'empty',
				'os': 'empty',
			}
		})
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
